//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS.IdeaPool.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Audit
    {
        public int Id { get; set; }
        public int TypeId { get; set; }
        public int LoginUserId { get; set; }
        public Nullable<int> IdeaId { get; set; }
        public string Description { get; set; }
        public Nullable<int> UpdateUserId { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual AuditType AuditType { get; set; }
        public virtual Idea Idea { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
