//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS.IdeaPool.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IdeaPoolEntities : DbContext
    {
        public IdeaPoolEntities()
            : base("name=IdeaPoolEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Activity> Activities { get; set; }
        public virtual DbSet<Audit> Audits { get; set; }
        public virtual DbSet<AuditType> AuditTypes { get; set; }
        public virtual DbSet<Discussion> Discussions { get; set; }
        public virtual DbSet<Exception> Exceptions { get; set; }
        public virtual DbSet<Feature> Features { get; set; }
        public virtual DbSet<FieldOfWater> FieldOfWaters { get; set; }
        public virtual DbSet<File> Files { get; set; }
        public virtual DbSet<ForgotPassword> ForgotPasswords { get; set; }
        public virtual DbSet<IdeaHistory> IdeaHistories { get; set; }
        public virtual DbSet<Idea> Ideas { get; set; }
        public virtual DbSet<IdeasFieldOfWater> IdeasFieldOfWaters { get; set; }
        public virtual DbSet<Login> Logins { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Setting> Settings { get; set; }
        public virtual DbSet<SettingsGroup> SettingsGroups { get; set; }
        public virtual DbSet<UnReadDiscussion> UnReadDiscussions { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<IdeaStatus> IdeaStatus { get; set; }
    }
}
