var FeatureKeys = {};
FeatureKeys = {
    SUBMIT_IDEA: 'SUBMIT_IDEA',
    VIEW_IDEAS_OF_OTHERS: 'VIEW_IDEAS_OF_OTHERS',
    UPDATE_IDEA_STATUS: 'UPDATE_IDEA_STATUS',
    USER_SEARCH: 'USER_SEARCH',
    USER_EDIT: 'USER_EDIT',
    SETTINGS_EDIT: 'SETTINGS_EDIT',
    EXPORT_IDEAS: 'EXPORT_IDEAS',
    PRINT_IDEA: 'PRINT_IDEA'
};

export default FeatureKeys